export enum GameEvents {
    INIT_REQUEST = 'INIT_REQUEST',
    INIT_RESPONSE = 'INIT_RESPONSE',

    SHOW_WINNINGS = 'SHOW_WINNINGS',

    INIT_GAME = 'INIT_GAME',
    INIT_COMPLETE = 'INIT_COMPLETE',

    IDLE_START = 'IDLE_START',

    SPIN_REQUEST = 'SPIN_REQUEST',
    SPIN_RESPONSE = 'SPIN_RESPONSE',

    SPIN_START = 'SPIN_START',

    SPIN_STOP = 'SPIN_STOP',
    SPIN_COMPLETE = 'SPIN_COMPLETE',

    SHOW_WAYS_START = 'SHOW_WAYS_START',
    SHOW_WAYS_COMPLETE = 'SHOW_WAYS_COMPLETE',

    STOP_FORTUNE_SYMBOLS = 'STOP_FORTUNE_SYMBOLS',
    STOP_FORTUNE_SYMBOLS_COMPLETE = 'STOP_FORTUNE_SYMBOLS_COMPLETE',

    ADD_LINE_START = 'ADD_LINE_START',
    ADD_LINE_COMPLETE = 'ADD_LINE_COMPLETE',

    RESET_LINES_START = 'RESET_LINES_START',
    RESET_LINES_COMPLETE = 'RESET_LINES_COMPLETE',

    START_FREESPINS_SHOW = 'START_FREESPINS_SHOW',
    FREESPINS_SHOW_COMPLETE = 'FREESPINS_SHOW_COMPLETE',

    STOP_FREESPINS_SHOW = 'STOP_FREESPINS_SHOW',
    STOP_FREESPINS_SHOW_COMPLETE = 'STOP_FREESPINS_SHOW_COMPLETE',

    BALANCE_UPDATE = 'BALANCE_UPDATE',
}